[global]
    work_root_path          = <work_root_path>
    run_path                = <run_path>
    run_name_suffix         = "italianpen"
    # net                     = "WeatherResNetUNet"
    net                     = "SmaAt_UNet"
    accumulate_grad_batches = 2
    save_data_path          = "data/numpy/"
    extra_data_path         = "data/extra/"
    figure_path             = "figures/"
    weights_path            = "data/weights/"
    print_date_strformat    = "%Y-%m-%d,%H:%M"
    log_level               = "info" # "debug"

[data]
    var_forecast            = "gh" # "t"    "u10"
    var_analysis            = "gh" # "T2M"  "U10M"
    error_limit             = 100 # 0 means no error limit
    levhpa                  = 500
    # Nord Atlantic box
    # source                  = "ecmwf"
    # lonini                  = -55
    # lonfin                  = -23
    # latini                  = 70 #35
    # latfin                  = 3
    # domain_size             = 256 # if set lonfin and latfin are ignored
    # interpolation_size      = 256
    # Italian peninsula box
    source                  = "cmcc"
    lonini                  = 5
    lonfin                  = 23.5
    latini                  = 49
    latfin                  = 25.5
    domain_size             = 128 # if set lonfin and latfin are ignored
    interpolation_size      = 128 # if different interpolation is triggered 
    detrend                 = false
    deseason                = false
    anomaly                 = false
    # acquisition_frequency   = "6h"
    forecast_delta          = 2
    download_path           = "data/ECMWF/"
    scaler_name             = "StandardScaler" # "RobustScaler" "MinMaxScaler"

[cmcc]
    forecast_path           = "/data/inputs/METOCEAN/rolling/model/atmos/ECMWF/IFS_010/1.0forecast/"
    analysis_path           = "/data/inputs/METOCEAN/historical/model/atmos/ECMWF/IFS_010/analysis/"
    # analysis_path           = "/data/inputs/METOCEAN/rolling/model/atmos/ECMWF/IFS_010/3.1analysis/"
    origin_frequency        = "12h"
    prod_freq_forecast      = "1h"
    prod_freq_analysis      = "6h"
    file_format_forecast    = "grib"
    file_format_analysis    = "grib" # "netcdf"

[ecmwf]
    ensemble_dataype        = "cf" # "pf"
    origin_frequency        = "6h"

[train]
    # 5 years training for cmcc italian peninsula dataset
    train_start_date        = "2020-01-01T00:00:00"
    train_end_date          = "2025-01-01T00:00:00"
    # train_end_date          = "2025-05-27T00:00:00"
    # annual training for ecmwf
    # train_start_date        = "2024-03-01T06:00:00"
    # train_end_date          = "2025-03-01T06:00:00"
    # train_end_date          = "2024-01-07T12:00:00"
[test]
    test_start_date         = "2025-03-02T00:00:00"
    test_end_date           = "2025-04-02T00:00:00"
    # test_start_date         = "2021-01-01T00:00:00"
    # test_end_date           = "2021-01-04T00:00:00"
    cmap                    = "magma"
    cmap_anomaly            = "RdBu"
    cmap_error              = "bwr"

[hyper]
    learning_rate           = [1e-4] # 5e-4, 1e-3
    batch_size              = [64] # important, 128 not working with SmaAt_UNet
    epochs                  = [400] # , 100, 200
    loss                    = ["MSELoss"] # "L1Loss", "CrossEntropyLoss", "BCEWithLogitsLoss"
    norm_strategy           = ["BatchNorm2d"] # "LayerNorm", "InstanceNorm2d"
    supervised              = [true]
